# Generated by Django 6.0.6 on 2026-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
