# Generated by Django 6.0.6 on 2026-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_profile_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hello',
            field=models.TextField(blank=True),
        ),
    ]
