# Generated by Django 6.0.6 on 2026-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0005_alter_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
