# Generated by Django 6.0.6 on 2026-09-30 14:48

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0006_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Optional product video (mp4, webm, mov or ogg). Shown before the image on the project card.', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='projects/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'ogg'])]),
        ),
    ]
